// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package sappurchaseorders.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import administration.proxies.microflows.Microflows;
import sappurchaseorders.proxies.PurchaseOrder;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SapGetPurchaseOrder extends CustomJavaAction<IMendixObject>
{
	private java.lang.String PurchaseOrderNumber;

	public SapGetPurchaseOrder(IContext context, java.lang.String PurchaseOrderNumber)
	{
		super(context);
		this.PurchaseOrderNumber = PurchaseOrderNumber;
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		PurchaseOrder obj = sappurchaseorders.proxies.microflows.Microflows.cON_GetPurchaseOrder(context(), PurchaseOrderNumber);
		return  obj != null ? obj.getMendixObject() : null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "SapGetPurchaseOrder";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
